[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npx prisma db push --accept-data-loss && node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
