[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
